### ISSUE TITLE
Stuck at It works!

### ISSUE THREAD

**Issue by AIDVP** [gsuitedevs/python-samples#100]
## Expected Behavior

expecting the creation of token.pickle. 

## Actual Behavior

The web page shows it works and console get stuck and nothing happened after that

## Steps to Reproduce the Problem

1. Download the sample
1. Install the libraries
1. Run the quickstart via python quickstart.py

## Specifications

- Python version (`python --version`) - 3.6
- OS (Mac/Linux/Windows) - Mac

![Screen Shot 2019-04-29 at 11 06 50 PM](https://user-images.githubusercontent.com/5667119/56939003-93b0ec00-6ad3-11e9-80e3-2d2a3ad0d68b.png)
![Screen Shot 2019-04-29 at 11 06 39 PM](https://user-images.githubusercontent.com/5667119/56939004-93b0ec00-6ad3-11e9-9c84-56ce2f870238.png)

**Comment by erickoledadevrel** [comment]
Are any errors reported on the command line?

**Comment by vanthoff10** [comment]
No errors. But not redirecting to a window. Any suggestions ?

**Comment by erickoledadevrel** [comment]
If you see the "It works!" text then it did redirect correctly. I'm not able to reproduce the problem, and without more information I can't further troubleshoot.
