### ISSUE TITLE
httplib2.SSLHandshakeError

### ISSUE THREAD

**Issue by abadcd** [gsuitedevs/python-samples#104]
Hello，I got the following error when I stepped through the documentation to the final step.
![image](https://user-images.githubusercontent.com/45786441/58093976-34da2080-7c02-11e9-918d-0338deac1710.png

**Comment by sqrrrl** [comment]
Looks like you might be using an old version of OpenSSL with Python. See this issue for some steps you can take to diagnose and fix the issue on your system.

**Comment by abadcd** [comment]
@sqrrrl thank you, Some related versions I am using：
Python 2.7.3
OpenSSL 1.1.1

**Comment by sqrrrl** [comment]
Sorry, forgot to link to the actual issue I wanted to point to -- https://github.com/pypa/pip/issues/829


Also, try running:

```
python -c "import ssl; print ssl.OPENSSL_VERSION"
```

And let me know what the output is.

**Comment by abadcd** [comment]
Thank you very much for keeping track of my problems, I get after running
OpenSSL 0.9.7l 28 Sep 2006

**Comment by sqrrrl** [comment]
Thanks. Definitely looks like the same issue described in the bug linked in my previous comment. There's not much we can do about that -- you'll just have to update your python version so it's linked against a more recent version of OpenSSL.

**Comment by abadcd** [comment]
@sqrrrl Awesome👍
Update the python version to the latest, it works for me。
thank you very much
