### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by lidatou1991** [gsuitedevs/python-samples#105]
## Expected Behavior
print out the contents of sample google sheets

## Actual Behavior
error message: socket timed out
## Steps to Reproduce the Problem

1. go to [here](https://developers.google.com/sheets/api/quickstart/python)
1. download `credentials.json` and save it where `quickstart.py` located
1. run the `quickstart.oy`

## Specifications
I am using shadowsocks-NG to access google server since I am in China. The VPS is a google cloud server with IP 35.xx.200.xxx. The HTTP proxy and Socks Proxy on my machine is 127.0.0.1:1088 and 127.0.0.1:1086.

I guess the problem is with network proxy since the auth flow has been completed.
 
I have also tried `gspread` and `pygsheet`, both raise same operation time out error as [detail description](https://github.com/nithinmurali/pygsheets/issues/307). Is there any solution?

`Traceback (most recent call last):
  File "gs-client.py", line 55, in <module>
    main()
  File "gs-client.py", line 38, in main
    service = build('sheets', 'v4', credentials=creds)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/googleapiclient/discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/googleapiclient/discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1926, in request
    cachekey,
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1501, in _conn_request
    conn.connect()
  File "/Users/limao/miniconda3/lib/python3.6/site-packages/httplib2/__init__.py", line 1289, in connect
    sock.connect((self.host, self.port))
socket.timeout: timed out
`
- Python version (`python --version`)
python 3.6
- OS (Mac/Linux/Windows)
Mac Mojave

**Comment by erickoledadevrel** [comment]
This issue seems to be unrelated to our sample code, and you are likely best following up on the issue tracker for the library.

The library at that point would be trying to download the discovery doc for the Sheets API, which is hosted at either:

https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
https://sheets.googleapis.com/$discovery/rest?version=v4

If you can't access these URLs due to your proxy settings then that would explain the problem.

**Comment by lidatou1991** [comment]
> This issue seems to be unrelated to our sample code, and you are likely best following up on the issue tracker for the library.
> 
> The library at that point would be trying to download the discovery doc for the Sheets API, which is hosted at either:
> 
> https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
> https://sheets.googleapis.com/$discovery/rest?version=v4
> 
> If you can't access these URLs due to your proxy settings then that would explain the problem.

I can access these URLs all, with response proper.

```
import socket

import socks

socket.setdefaulttimeout(150)

socks.set_default_proxy(socks.SOCKS5, "127.0.0.1", 1086)
socket.socket = socks.socksocket
```
After 4 days search, the problem is solved in [answer here].(https://stackoverflow.com/questions/56300950/pygsheet-operation-time-out-errno-60). Thank you.
