### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json' -- Despite it being there

### ISSUE THREAD

**Issue by AlecMcMeen** [gsuitedevs/python-samples#118]
Hello,

I am currently trying to follow the steps shown [HERE](https://developers.google.com/admin-sdk/directory/v1/quickstart/python) for the Admin SDK Directory. I've downloaded my Credentials.json file, and have moved it into the directory along with the quickstart.py file. 

[Files in same directory](https://i.imgur.com/h98Pw4k.png)

After running `python C:\Users\amcmeen\Desktop\Pyth_Direc\Quickstart\quickstart.py` I am replied with- 

`PS C:\Windows\system32> python C:\Users\amcmeen\Desktop\Pyth_Direc\Quickstart\quickstart.py
Traceback (most recent call last):
  File "C:\Users\amcmeen\Desktop\Pyth_Direc\Quickstart\quickstart.py", line 52, in <module>
    main()
  File "C:\Users\amcmeen\Desktop\Pyth_Direc\Quickstart\quickstart.py", line 28, in main
    'credentials.json', SCOPES)
  File "C:\Users\amcmeen\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google_auth_oauthlib\flow.py", line 180, in from_client_secrets_file
    with open(client_secrets_file, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'`

Thinking that maybe it was an issue with the credentials.json file I originally downloaded, I went and downloaded it again but had the same results. 

I feel like this is a simple issue that I'm messing up at one step or putting it in the wrong location, but after about 45 minutes I can't seem to figure it out on my own.

Thank you for your assistance.

**Comment by sqrrrl** [comment]
I think the issue is it's expecting the working directory to be the same as where the files are. Try:

```
cd C:\Users\amcmeen\Desktop\Pyth_Direc\Quickstart\
python quickstart.py
```

**Comment by AlecMcMeen** [comment]
> I think the issue is it's expecting the working directory to be the same as where the files are. Try:
> 
> ```
> cd C:\Users\amcmeen\Desktop\Pyth_Direc\Quickstart\
> python quickstart.py
> ```

That worked perfectly. Thank you.

**Comment by PVkolos** [comment]
### 

> 

- `_**ывыфвыфвыфвыфвыфвыыфвыфвыфвыфввыф

1. 

- [ ]   #@ыфывфыфыфыфв

**_`

**Comment by Incognitosamer** [comment]
Can you tell this noob how to download that creadentials.json file

**Comment by pgdada** [comment]
> Can you tell this noob how to download that creadentials.json file

did you find an answer to this?

**Comment by codeilm** [comment]
> Can you tell this noob how to download that creadentials.json file

You can download it from Firebase project setting

**Comment by codeilm** [comment]
> Where is credentials.json? I cant seem to find it.

You can download it from Firebase project setting
