### ISSUE TITLE
quickstart for Contact API

### ISSUE THREAD

**Issue by SpiritualDixit** [gsuitedevs/python-samples#126]
Can you please add a quickstart for Contact API because when I tried to use Contacts API using discovery, got a error:

googleapiclient.errors.HttpError: <HttpError 403 when requesting https://contacts.googleapis.com/$discovery/rest?version=v3 returned "The request is missing a valid API key.">

**Comment by sqrrrl** [comment]
Use the newer People API instead.

https://people.googleapis.com/$discovery/rest?version=v1

There are some getting started instructions at https://developers.google.com/people/
