### ISSUE TITLE
Useless if running in a shell on a remote machine

### ISSUE THREAD

**Issue by nyetwurk** [gsuitedevs/python-samples#127]

**Comment by kovkev** [comment]
# Make sure the script has             creds = flow.run_local_server(port=1234)
> ssh -L 1234:localhost:1234 ubuntu@myremote
>> python authenticate.py
Please visit this URL to authorize this application: https:////accounts.google.com/o/oauth2/auth .... 
# Visit that url
# Follow the steps
# It'll visit localhost:1234 which points to myremote
