### ISSUE TITLE
ModuleNotFoundError: No module named 'googleapiclient'

### ISSUE THREAD

**Issue by premananda8** [gsuitedevs/python-samples#128]
python vers:3.7 : package "googleapiclient" not installing.
When installing this package i'm getting following error:
Collecting googleapiclient

  Could not find a version that satisfies the requirement googleapiclient (from versions: )
No matching distribution found for googleapiclient

**Comment by sqrrrl** [comment]
That's not the correct package name to install. See https://github.com/gsuitedevs/python-samples/blob/master/calendar/quickstart/requirements.txt for which packages to install.

If there's a doc or instructions somewhere that incorrectly show the package name, please file another bug or reopen this so we can fix it.

**Comment by afrikaquality** [comment]
pip install google-api-python-client

**Comment by vats147** [comment]
> 

How to import ??
