### ISSUE TITLE
Cant enable API Key

### ISSUE THREAD

**Issue by OleGrue** [gsuitedevs/python-samples#130]
## Expected Behavior
Go to the Website developers.google.com/calendar and enable API key.

## Actual Behavior
Cant access because I am younger than 16 years old.

## Steps to Reproduce the Problem

1. Create google account younger than 16
2. Log into Chrome
3. Go to developers.google.com

## Specifications

- Chrome or Firefox

**Comment by sqrrrl** [comment]
Can you include the error message you see?

**Comment by OleGrue** [comment]
![Sreenshot](https://user-images.githubusercontent.com/49246995/65905701-5b367680-e3c1-11e9-878c-979d8c13871f.png)

**Comment by sqrrrl** [comment]
Thanks. Unfortunately not much I can do to help at the moment as this is more of a policy/compliance issue and the behavior is working as intended.
