### ISSUE TITLE
No module named 'googleapiclient'

### ISSUE THREAD

**Issue by elfranco91** [gsuitedevs/python-samples#144]
## Actual Behavior
No module named 'googleapiclient'

## Steps to Reproduce the Problem

1. run quckstart.py
1.
1.

## Specifications

- Python version (`3.7.4`)
- OS (Windows)

`

from __future__ import print_function
import datetime
import pickle
import os.path
from googleapiclient.discovery import build

from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/calendar.readonly']

def main():
    """Shows basic usage of the Google Calendar API.
    Prints the start and name of the next 10 events on the user's calendar.
    """
    creds = None
    # The file token.pickle stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    service = build('calendar', 'v3', credentials=creds)

    # Call the Calendar API
    now = datetime.datetime.utcnow().isoformat() + 'Z' # 'Z' indicates UTC time
    print('Getting the upcoming 10 events')
    events_result = service.events().list(calendarId='primary', timeMin=now,
                                        maxResults=10, singleEvents=True,
                                        orderBy='startTime').execute()
    events = events_result.get('items', [])

    if not events:
        print('No upcoming events found.')
    for event in events:
        start = event['start'].get('dateTime', event['start'].get('date'))
        print(start, event['summary'])

if __name__ == '__main__':
    main()
`

**Comment by elfranco91** [comment]
im new to python so im struggling with this one

**Comment by sqrrrl** [comment]
From the error, likely that you just missed a step in the instructions. See https://developers.google.com/calendar/quickstart/python and make sure to complete step 2.

**Comment by elfranco91** [comment]
Thank you, worked straight away
