### ISSUE TITLE
cannot import name 'errors' in qickstart.py

### ISSUE THREAD

**Issue by trevorpeacock** [gsuitedevs/python-samples#20]
`apps_script/quickstart/quickstart.py` reffers to `errors.HttpError`. 
https://github.com/gsuitedevs/python-samples/blob/2c871ce0c223b62a91ff0347f5f9eee749f5cffc/apps_script/quickstart/quickstart.py#L57
errors is not defined
```
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from apiclient.discovery import build, errors
ImportError: cannot import name 'errors'
```
I'm guessing the resolution is to add
```
from apiclient import errors
```
works for me.

**Comment by erickoledadevrel** [comment]
Thanks for reporting this issue!
