### ISSUE TITLE
admin_sdk/reports/quickstart.py HttpError 401 Access Denied

### ISSUE THREAD

**Issue by codyznash** [gsuitedevs/python-samples#21]
I'm attempting to follow the [quickstart for the Admin SDK](https://developers.google.com/admin-sdk/reports/v1/quickstart/python).

After authentication I get the following output from the quickstart.py:

> Authentication successful.
Getting the last 10 login events
Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    results = service.activities().list(userKey='all', applicationName='login',maxResults=10).execute()
  File "..\Miniconda2\envs\default\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "..\Miniconda2\envs\default\lib\site-packages\googleapiclient\http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 401 when requesting https://www.googleapis.com/admin/reports/v1/activity/users/all/applications/login?alt=json&maxResults=10 returned "Access denied. You are not authorized to read activity records.">

**Comment by erickoledadevrel** [comment]
As per the requirements listed in that guide, you need "A Google account in that domain with administrator privileges."

**Comment by erickoledadevrel** [comment]
It's referring to your Google account's privileges in the G Suite domain, not it's privileges on the Google Developers Console project.

**Comment by codyznash** [comment]
Okay, thank you!

**Comment by Srajangpt1** [comment]
I am getting the same error and I have looked over all supporting articles but couldn't resolve this issue. Here is the code -
`from __future__ import print_function

import os.path
from google.oauth2 import service_account
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/admin.reports.audit.readonly']
SERVICE_ACCOUNT_FILE = 'credentials.json'
credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE, scopes=SCOPES)
def main():
    """Shows basic usage of the Admin SDK Reports API.
    Prints the time, email, and name of the last 10 login events in the domain.
    """
    service = build('admin', 'reports_v1', credentials=creds)

    # Call the Admin SDK Reports API
    print('Getting the last 10 login events')
    results = service.activities().list(userKey='all', applicationName='token',
                                        maxResults=10).execute()
    print(results)
    activities = results.get('items', [])

    if not activities:
        print('No logins found.')
    else:
        print('Logins:')
        for activity in activities:
            print(activity)


if __name__ == '__main__':
    main()`

Please suggest what am I doing wrong?
