### ISSUE TITLE
Can't locate apiclient module

### ISSUE THREAD

**Issue by acidmonsta** [gsuitedevs/python-samples#26]
Keep getting this error :
ImportError: No module named apiclient.discovery

**Comment by grant** [comment]
Which sample? Did you follow the sample instructions?

**Comment by keyrea1** [comment]
Same here. I fixed this by typing "from googleapiclient.discovery import build" instead of "from apiclient.discovery import build"

**Comment by grant** [comment]
Thanks. This issue has since been fixed.
Please comment here if you're still facing this issue.
