### ISSUE TITLE
Sample for Google Sheets needs additional documentation

### ISSUE THREAD

**Issue by amjadtalib** [gsuitedevs/python-samples#32]
I just want to reference this issue [#299](https://github.com/google/google-api-python-client/issues/299#issuecomment-268915510) and solution provided by @maxrp to silence an error.

Judging by the reactions, I think this would be useful to include in the [sample](https://developers.google.com/sheets/api/quickstart/python) if possible!

**Comment by grant** [comment]
It looks like that issue recommends:

```py
cache_discovery=False
```
as an option in the `build()` command.

Also consider:

```py
import logging
logging.getLogger('googleapiclient.discovery').setLevel(logging.CRITICAL)
```

**Comment by sqrrrl** [comment]
Or wait for googleapis/google-api-python-client#325 to be fixed.

**Comment by asrivas** [comment]
Looks like googleapis/google-api-python-client#325 was fixed
