### ISSUE TITLE
sorry, I don't know what token.json, and code gives KeyError: '_module'

### ISSUE THREAD

**Issue by ldta2018** [gsuitedevs/python-samples#43]
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Python version (`python --version`)
- OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment]
See here for how to resolve this issue: https://github.com/gsuitedevs/python-samples/issues/38#issuecomment-424353702
