### ISSUE TITLE
Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by travelmail26** [gsuitedevs/python-samples#51]
## Expected Behavior
ran the script from the quick start guide. installed credentials.json and activated google scripts API

## Actual Behavior
Get this error "Request had insufficient authentication scopes"

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Python version (`python --version`)
- OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment]
Which quick start in particular are you referring to?

**Comment by travelmail26** [comment]
I ended up fixing my issue with another app. thanks for responding
