### ISSUE TITLE
Cannot uninstall 'six'. It is a distutils installed project...

### ISSUE THREAD

**Issue by iViollard** [gsuitedevs/python-samples#58]
## Expected Behavior

I am trying to follow the Python quickstart guide - what should happen when running 

`python quickstart.py
`

is what is described in the page: [Drive API Python Quickstart](https://developers.google.com/drive/api/v3/quickstart/python)

## Actual Behavior

I run into an error:

When running python quickstart.py:

```
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from googleapiclient.discovery import build
ImportError: No module named googleapiclient.discovery
```

## Steps to Reproduce the Problem

1. `pip install --upgrade google-api-python-client oauth2client`
2. `python quickstart.py`

## Specifications

- Python version 2.7.10
- OS Mojave 10.14.1

**Comment by erickoledadevrel** [comment]
Try adding the flags `-ignore-installed six` to your `pip` command and let me know if that works.

**Comment by iViollard** [comment]
@erickoledadevrel thanks for replying. i tried the following:

`pip install --upgrade google-api-python-client -ignore-installed six oauth2client`
`pip install --upgrade google-api-python-client-ignore-installed six oauth2client`

Both give me an error:

'Could not find a version that satisfies the requirement google-api-python-client (from versions: )
No matching distribution found for google-api-python-client'

'Could not find a version that satisfies the requirement google-api-python-client-ignore-installed (from versions: )
No matching distribution found for google-api-python-client-ignore-installed'

**Comment by erickoledadevrel** [comment]
Sorry, that should have been `--ignore-installed` with two dashes. Please try again.

**Comment by iViollard** [comment]
that's solved it - thanks!

**Comment by erickoledadevrel** [comment]
FYI, this information has been added to the troubleshoot section of the quickstart:

https://developers.google.com/drive/api/v3/quickstart/python#troubleshooting

**Comment by qmikep** [comment]
This solution does not work on Ubuntu. Still get

`ModuleNotFoundError: No module named 'googleapiclient'`

**Comment by shaka0241** [comment]
> Try adding the flags `--ignore-installed six` to your `pip` command and let me know if that works.

its works

**Comment by dpizzuto** [comment]
> Try adding the flags `--ignore-installed six` to your `pip` command and let me know if that works.

It works.

**Comment by brando90** [comment]
when do we know we should ignore six and when to ignore it?

**Comment by bashar13** [comment]
it works thank you @erickoledadevrel

**Comment by 490058** [comment]
Thank you! @erickoledadevrel

**Comment by gt-novelt** [comment]
If you are working with *pipenv*, you can achieve this by editing your **Pipefile** with

    six = {version = "*", options = "--ignore-installed"}
