### ISSUE TITLE
Instance of 'Resource' has no 'users' member

### ISSUE THREAD

**Issue by sivankatz** [gsuitedevs/python-samples#67]
## Expected Behavior
No errors

## Actual Behavior
"Instance of 'Resource' has no 'users' member"

## Steps to Reproduce the Problem

1. Run the code

## Specifications

- Python version (`python --version`) 3.7.
- OS (Mac/Linux/Windows) windows 10

**Comment by erickoledadevrel** [comment]
Which specific quickstart were you trying to run?

**Comment by sqrrrl** [comment]
Looks like admin-sdk/directory given the reference to users. 

But since I haven't been able to reproduce this (tried using non admin, delegated admin, etc) and there's been no response in 2 months to clarify, closing the bug.
