### ISSUE TITLE
Problem when using quick start in virtualenv

### ISSUE THREAD

**Issue by oconnellamethyst** [gsuitedevs/python-samples#73]
## Expected Behavior
For it to run

## Actual Behavior
Traceback (most recent call last):
  File "/home/amethyst/gmail.py", line 4, in <module>
    from googleapiclient.discovery import build
ImportError: No module named 'googleapiclient'

## Steps to Reproduce the Problem

```BASH
~$ virtualenv gmail
~$ source ./gmail/bin/activate
~$ pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
```

In IDLE, create the program from the tutorial and run it.

## Specifications

- Python version (`python --version`)
Python 3.5.2
- OS (Mac/Linux/Windows)
Ubuntu 16.04

**Comment by ZxBiohazardZx** [comment]
please ensure the correct plugin is actually installed.

Im using the Py3 port: 
pip install -- upgrade google-api-python-client-py3 google-auth-httplib2 google-auth-oauthlib

 i managed to get through the googleapiclient problem there

**Comment by alew3** [comment]
I have the same problem using Anaconda virtual env.

ImportError: cannot import name 'build' from 'googleapiclient.discovery'

**Comment by alew3** [comment]
I have the same issue with Anaconda virtual env.
ImportError: cannot import name 'build' from 'googleapiclient.discovery'
I tried using the google-api-python-client-py3, but it didn't work either.

**Comment by erickoledadevrel** [comment]
I still haven't been able to repro this behavior. If you can narrow down the issue further I'll be happy to take another look.
