### ISSUE TITLE
cant run people quickstart.py

### ISSUE THREAD

**Issue by vothanhhai** [gsuitedevs/python-samples#75]
## Expected Behavior
as I just copy your sample, expected that it can run as designed

## Actual Behavior
 
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

and if run on Pycharm, there is a message: ModuleNotFoundError: No module named 'googleapiclient'
if run in cmd shell, it seems to be OK until it print a message: 
Getting the first 10 users in the domain

then error message

Traceback (most recent call last):
  File "contact.py", line 48, in <module>
    main()
  File "contact.py", line 36, in main
    results = service.users().list(customer='my_customer', maxResults=10, orderBy='email').execute()
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/admin/directory/v1/users?customer=my_customer&maxResults=10&orderBy=email&alt=json returned "Domain not found.">

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Python version 3.7.2
- OS Windows10
- pycharm

**Comment by erickoledadevrel** [comment]
I'm not sure how pycharm works, but if it works in the shell then it seems like the code is fine and pycharm is having a problem with the dependencies. The 404 error is likely due to running the account using an @gmail.com account and not a G Suite admin account as required in the instructions.

**Comment by vothanhhai** [comment]
Thank you for your email. Yes, this is gmail account, not gsuit.

Do you have any sample using gmail account, if yes, please update your code. Thank a lot

Best regards
Vo Thanh Hai

________________________________

**Comment by erickoledadevrel** [comment]
More information is available here: https://developers.google.com/admin-sdk/directory/v1/guides/manage-users#retrieve_users_non_admin
