### ISSUE TITLE
How to get sign in and sign out time of G-Suite(Calendar,Gmail,Drive)?

### ISSUE THREAD

**Issue by dapsjj** [gsuitedevs/python-samples#76]
I want to get sign in and sign out time of G-Suite(Calendar,Gmail,Drive).

Is there a google-api that can get such data?

I find google-api from this [link](https://developers.google.com/gsuite/aspects/apis/overview),but I can't find the API for getting sign in and sign out time.

How can I get sign in and sign out time without the api?

**Comment by sqrrrl** [comment]
I think your best bet is the reports API -- https://developers.google.com/admin-sdk/reports/v1/appendix/activity/login
