### ISSUE TITLE
Gets stuck at "Enable the Drive API"

### ISSUE THREAD

**Issue by ShidaPenns** [gsuitedevs/python-samples#77]
## Expected Behavior
https://developers.google.com/drive/api/v3/quickstart/python
You click the "ENABLE THE DRIVE API" button in step 1 and it's supposed to create a file called "credentials.json".

## Actual Behavior
I click the "ENABLE THE DRIVE API" button, it loads a dialog, which gets to "Enable the Drive API" and stays there. I've tried different browsers, same problem (after I log into my Drive account). Am I being an idiot? It's a common problem for me.
I don't get any error message, it just stays on that.

## Steps to Reproduce the Problem
I don't know how to reproduce it for other people.

## Specifications
- Python version (`python --version`)
3.7.0
- OS (Mac/Linux/Windows)
Windows 10

**Comment by erickoledadevrel** [comment]
It looks like a recent change to the button code broke the flow for users that hadn't already accepted the terms of service. We've reverted the change, please try again.
