### ISSUE TITLE
Which api of G-Suite(Calendar,Gmail,Drive) can get gmail address for all staff when use administrator account?

### ISSUE THREAD

**Issue by dapsjj** [gsuitedevs/python-samples#78]
I use google-calendar-api to get events data of calendar form this [link](https://developers.google.com/calendar/v3/reference/events/list?authuser=1).

The parameter calendarId is gmail account.

In my company, I have a GSuite administrator account.

I want to get the Gmail account of the staff.

Now because I know some people's Gmail account, for example, I have 100 people's accounts. But if new employees come to the company, I don't know the Gmail account of these new employees.

So if these new employees have their new gmail of company, can I also get there new gmail with administrator account?

Which api or where can I get full staff's gmail?

**Comment by sqrrrl** [comment]
Try https://developers.google.com/admin-sdk/directory/
