### ISSUE TITLE
problem with running quickstart

### ISSUE THREAD

**Issue by ExodoJaffar** [gsuitedevs/python-samples#79]
## Steps to Reproduce the Problem

1.Run quickstart
1.
1.
## Error return 

{
  "error": 
    "code": 403,
    "message": "User has not enabled the Apps Script API. Enable it by visiting https://script.google.com/home/usersettings then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
   "errors": [
      {
        "message": "User has not enabled the Apps Script API. Enable it by visiting https://script.google.com/home/usersettings then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
       "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
'

## Specifications

- Python version `3.6`
- OS Windows

**Comment by AmalVijayan** [comment]
Hi,

I have been trying to execute an App Script with the execute.py. I am the below error,

b'{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "errors": [\n      {\n        "message": "The caller does not have permission",\n        "domain": "global",\n        "reason": "forbidden"\n      }\n    ],\n    "status": "PERMISSION_DENIED"\n  }\n}\n'

Spec : 
Python 3
Mac

**Comment by erickoledadevrel** [comment]
@ExodoJaffar - The error message is pretty clear about the cause of the problem and how to resolve it. Please follow the steps it outlines.

@AmalVijayan - That error indicates that the user that authorized the Python application doesn't have at least view access on the target script. Please check that you are using the same account for both.
