### ISSUE TITLE
ValueError: Client secrets must be for a web or installed app.

### ISSUE THREAD

**Issue by sheruaravindreddy** [gsuitedevs/python-samples#87]
```py
if __name__ == '__main__':
     main()

         else:
             flow = InstalledAppFlow.from_client_secrets_file(
                 'credentials.json', SCOPES)
             creds = flow.run_local_server()

             client_config = json.load(json_file)
 
         return cls.from_client_config(client_config, scopes=scopes, **kwargs)
 
     @property

/anaconda/envs/py35/lib/python3.5/site-packages/google_auth_oauthlib/flow.py in from_client_config(cls, client_config, scopes, **kwargs)
         else:
             raise ValueError(
                 'Client secrets must be for a web or installed app.')
 
         session, client_config = (
```

## Specifications

- Python version (`python --3.5`)
- OS (Linux)

**Comment by erickoledadevrel** [comment]
As the error indicates, you likely have the wrong type of client or content in `credentials.json`. Please use the button in the quickstart to download the correct credentials.

**Comment by x011** [comment]
>  Please use the button in the quick start to download 
truly helpful...

**Comment by coopslarhette** [comment]
for me, I had accidentally on purpose lopped of the "web" key in my json such that the credentials weren't nested under `"web"`

looked at the [source code here](https://googleapis.dev/python/google-auth-oauthlib/latest/_modules/google_auth_oauthlib/helpers.html), it will throw this error if a key of "web" or "installed" isn't present
