### ISSUE TITLE
flow.run_local_server() raises AttributeError

### ISSUE THREAD

**Issue by StasDeep** [gsuitedevs/python-samples#88]
## Expected Behavior
Work fine as here: https://developers.google.com/gmail/api/quickstart/python.

## Actual Behavior
After clicking "Allow" button (second time) in browser and redirection to local page, browser shows "This site can't be reached" error. In console script, the following error occurs:

```
Traceback (most recent call last):
  File "script.py", line 48, in <module>
    main()
  File "script.py", line 29, in main
    creds = flow.run_local_server(port=8088)
  File "/Users/stasdeep/.virtualenvs/gmail/lib/python3.6/site-packages/google_auth_oauthlib/flow.py", line 418, in run_local_server
    authorization_response = wsgi_app.last_request_uri.replace(
AttributeError: 'NoneType' object has no attribute 'replace'
```

## Steps to Reproduce the Problem

1. Create a virtualenv: `mkvirtualenv -p python3.6 gmail`
2. Enable Gmail API
3. Install requirements: `pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib`
4. Run the quickstart script: `python quickstart.py`

## Specifications

- Python 2.7/3.6 (envs created with `virtualenvwrapper`)
- macOS Mojave 10.14.1

**Comment by erickoledadevrel** [comment]
You mention clicking the Allow button a second time, can you further explain the flow you went through? You should only be prompted once, and I'm wondering if that's related to the error.

**Comment by StasDeep** [comment]
@erickoledadevrel yes, that's what I've noticed, too, because with Spreadsheets API I don't have this first pop-up window.

Here it is, the pop-up window:
![image](https://user-images.githubusercontent.com/17574404/53930175-4f086600-40cb-11e9-975e-fe1ab851941a.png)

After that, this page is shown.
![image](https://user-images.githubusercontent.com/17574404/53930186-61829f80-40cb-11e9-86ee-4015315ed909.png)

I've tested my code with Spreadsheets API that used to work, and there is the same error as with the Gmail API (no pop-up window though).
Could it be that something is wrong with my account?

**Comment by erickoledadevrel** [comment]
It looks like it's a change to the OAuth flow that is enabled on new Cloud projects, and is unrelated to your error. Your error indicates that the library is for some reason not capturing the redirect URL properly. Does this error happen consistently? Can you confirm that the application is pausing while you are going through the OAuth flow?

**Comment by StasDeep** [comment]
@erickoledadevrel yes, this error happens consistently, I am still not able to use Gmail API or Sheets API.

**Comment by erickoledadevrel** [comment]
To my last question, if the application waiting while you are completing the OAuth flow in the browser, or is it failing immediately?

**Comment by StasDeep** [comment]
It is failing as soon as I click “Allow” button  (the second one in the case of Gmail API).

**Comment by StasDeep** [comment]
The problem has disappeared by itself.

**Comment by codingsett** [comment]
I am facing this issue any fix

**Comment by dwanneruchi** [comment]
> I am facing this issue any fix

I am also

**Comment by gitars** [comment]
I had this issue repeatedly and tried just copying the URL the quickstart.py file opened to a new incognito window and it worked.

**Comment by Elysweyr** [comment]
I had to submit the `success_message` param in the `run_local_server()` call (e.g. `run_local_server(success_message='test'))`.
In flow.py `replace()` is called on a NoneType because the default values aren't set properly so you have to override them.

**Comment by RedTech64** [comment]
I am still having this issue. Tried doing it in Incognito and it still isn't working.

**Comment by Elysweyr** [comment]
> I am still having this issue. Tried doing it in Incognito and it still isn't working.

You may check out my answer.

**Comment by RedTech64** [comment]
@Elysweyr I ended up moving the oauth flow to the route using the service, rather than in the main method and it seemed to work. It's still a bit finicky, however.

**Comment by arpitmailgun** [comment]
> I am still having this issue. Tried doing it in Incognito and it still isn't working.

I had the same issue. I ended up switching to the Chrome browser from Safari and it worked, weird but it worked for me.

**Comment by bdnettleton** [comment]
Had this problem as well in Safari; but it worked when I put the authorization url into FireFox.

**Comment by philiphoyos** [comment]
> Had this problem as well in Safari; but it worked when I put the authorization url into FireFox.

This solved it for me too. The auth flow did not work with Chrome, but worked in Firefox.

**Comment by mzw4** [comment]
The issue for me was I needed to clear my HSTS settings for localhost. It was set up (from other work I'm doing) to redirect localhost to https, so it was trying to hit https://localhost

Enter "localhost" into Delete domain security policies at: chrome://net-internals/#hsts
