### ISSUE TITLE
AttributeError: module 'json' has no attribute 'load' 

### ISSUE THREAD

**Issue by ktprezes** [gsuitedevs/python-samples#92]
## Expected Behavior

successful run of calednar-quickstart.py example

## Actual Behavior

**prompt>** python gcal-quick-start.py
Traceback (most recent call last):
  File "quickstart.py", line 53, in <module>
    main()
  File "quickstart.py", line 30, in main
    SCOPES)
  File "D:\Program Files2\Python\lib\site-packages\google_auth_oauthlib\flow.py", line 172, in from_client_secrets_file
    client_config = json.load(json_file)
AttributeError: module 'json' has no attribute 'load'

## Steps to Reproduce the Problem

1. Make all the steps from site:<br>https://developers.google.com/calendar/quickstart/python
1. get an error :(
1. I've deleted (ok, renamed) all *.pyc files - according to some stackoverflow answers to similar problems, but this error persists :(
1. It doesn't matter if I'm trying to run this example in 'normal' or 'virtual' environment

## Specifications

- Python version (`python --version`): Python 3.7.2
- OS (Mac/Linux/Windows): Windows 8.1 64-bit

**Comment by erickoledadevrel** [comment]
It seems like the most common cause of this problem is that you have a file named `json.py` in your directory that Python is importing instead of the correct dependency. Please check that there isn't any conflicting module.

**Comment by kkarnik22** [comment]
Thank you.

**Comment by MYHINDA** [comment]
i have the same problem without this file

**Comment by malomodaniels** [comment]
I don't have any file name json yet its showing error

**Comment by erm3nda** [comment]
I got this error by trying to read json string from empty file. I just added a `if file.read():` before.

**Comment by OgadaOgada** [comment]
> It seems like the most common cause of this problem is that you have a file named `json.py` in your directory that Python is importing instead of the correct dependency. Please check that there isn't any conflicting module.

Thanks, this helped me

**Comment by mjd0690** [comment]
thanks. this helped me alot
